package me.suncatmc.turtleTime

object CodeUnit {
    const val GRASS = '#'
    const val WALL = 'X'
    const val SOFT_WALL = 'S'
    const val WATER = '~'
    const val ICE = '_'
    const val CONDITION = '?'
    const val INPUT_CH = 'i'
    const val INPUT_NUM = 'I'
    const val HOUSE_CH = '&'
    const val HOUSE_NUM = '$'
    const val DUPE_HOR = '='
    const val DUPE_VER = '|'
    const val PLUS = '+'
    const val MINUS = '-'
    const val DIV = '/'
    const val MOD = '%'
    const val MUL = '*'
    const val PORTAL_A = 'a'
    const val PORTAL_B = 'b'
    const val PORTAL_C = 'c'
    const val PORTAL_D = 'd'
    const val PORTAL_E = 'e'
    const val PORTAL_F = 'f'
    const val CONVEYOR_UP = '^'
    const val CONVEYOR_DOWN = 'v'
    const val CONVEYOR_LEFT = '<'
    const val CONVEYOR_RIGHT = '>'
    const val TURTLE_MAIN = 'O'
    const val TURTLE_WATER = 'o'
    const val TURTLE_ICE = '!'
}